version: "3.8"
services:
  front-end:
    depends_on:
      - monolith
    build:
      context: ./frontend
      target: dev
    volumes:
      - ./frontend/html:/usr/share/nginx/html
    ports:
      - 80:80
  monolith:
    depends_on:
      - monolith-postgres
    build:
      context: ./monolith
      target: dev
    volumes:
      - ./monolith:/work/
    environment:
      - PORT=3000
      - POSTGRES_DATABASE_URL=postgres://user:password@monolith-postgres:5432/postgres
    ports:
      - 3000:3000
  monolith-postgres:
    image: postgres:11.2-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
